version: "3"
services:
  nestjs-app:
    image: 958569661612.dkr.ecr.eu-north-1.amazonaws.com/horbas-genesis-api
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - postgres
    networks:
      - common
    environment:
      NODE_ENV: production

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
    networks:
      - common

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - postgres
      - nestjs-app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - common

volumes:
  docker-nest-postgres:
    driver: local
networks:
  common:
    driver: bridge